### ISSUE TITLE
Feature Request: Enable Bazel Starlark Linting and Formatting

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#126]
## Tasks
- [x] Add Bazel target that can be used to check for lint and formatting issues using Buildifier
- [x] Add Bazel target that can fix lint and formatting issues using Buildifier.
- [ ] Update the existing codebase to address existing lint and formatting issues.
- [ ] Update the CI pipeline to execute the check target.

## Suggested Implementation
- First PR
  - Add [keith/buildifier-prebuilt](https://github.com/keith/buildifier-prebuilt) as a dev-only dependency.
  - Implement two runnable Bazel targets: one to check the lint issues and one to fix issues.
- Second PR
  - Fix all of the existing lint issues 
  - Add another entry to `bazel_commands` in the `buildbuddy.yml` file to execute the check Bazel target.
