### ISSUE TITLE
Enable all Buildifier warnings

### ISSUE THREAD

**Issue by cgrindel** [buildbuddy-io/rules_xcodeproj#176]
By default, Buildifier does not enable all warnings. One needs to configure Buildifier to apply all defined warnings.

## Tasks
- [x] Enable all warnings
- [x] Exclude `cc-native` warnings
- [x] Remove exclusion for `examples/ios_app/Utils/BUILD`.

**Comment by cgrindel** [comment]
Once a new release of [keith/buildifier-prebuilt](https://github.com/keith/buildifier-prebuilt) occurs, I have a PR that will close this issue.
