### ISSUE TITLE
Support `apple_static_framework_import`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#71]
https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#apple_static_framework_import

- [x] https://github.com/buildbuddy-io/rules_xcodeproj/pull/211
- [ ] Support `alwayslink`: #608
- [x] Support `deps`
- [x] Support `sdk_dylibs`: #372
- [x] Support `sdk_frameworks `: #278
- [x] Support `weak_sdk_frameworks `: #278
