### ISSUE TITLE
Support `{ios_*,macos,tvos,watchos}_extension`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#72]
- [x] Bundled correctly: #689 
- [x] Correct schemes: #723
- [ ] Support `app_icons`: #730
- [x] Support `codesignopts`: #593 
- [x] Support `entitlements`: #367
- [X] Support `executable_name`: #721
- [x] Support `exported_symbols_lists`: #649 
- [ ] Support `frameworks`: #78 
- [x] Support `infoplists`: #225
- [x] Support `provisioning_profile`
- [x] Support `resources`: #208 
- [x] Support `sdk_frameworks`
- [ ] Support `strings`
- [x] Support `version`: #74
