### ISSUE TITLE
Support `{ios,tvos,watchos}_framework`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#78]
- [x] Support `codesignopts`: #593 
- [X] Support `executable_name`: #721
- [x] Support `exported_symbols_lists`: #649 
- [x] Support `extension_safe`: #1165
- [ ] Support `hdrs`: #1178
- [x] Support `infoplists`: #225
- [x] Support `provisioning_profile`
- [x] Support `resources`: #208
- [x] Support `strings`: #1176
- [x] Support `version`: #74
