### ISSUE TITLE
Support `{ios,macos,tvos,watchos}_application`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#96]
- [x] `ios_application`
- [x] `macos_application`
- [x] `tvos_application`
- [x] `watchos_application`

For each:
- Check if it's already supported, and if not, make required changes
- Add an example
- Add a fixture test

For `watchos_application`:
- [x] Also support "WatchApp for iOS App" with "Embed Watch Content" `PBXCopyFilesBuildPhase `: #718 

Non-minimal fields that need support:
- [x] Fully support `app_icons`: #730
- [x] Support `alternate_icons`: #1125
- [x] Support `codesignopts`: #593
- [x] Support `entitlements`: #367
- [x] Support `executable_name`: #721
- [x] Support `frameworks`: #1163
- [x] Support `infoplists`: #225
- [x] Support `launch_images`: #713
- [x] Support `launch_storyboard`: #712
- [x] Support `provisioning_profile`
- [ ] https://github.com/buildbuddy-io/rules_xcodeproj/issues/1653
- [x] Support `strings`: #1176

**Comment by maxwellE** [comment]
@brentleyjones For the "Non-minimal fields that need support", are we saying that those are not supported at all right now?

**Comment by brentleyjones** [comment]
They might be supported, but we don't have examples of them if they aren't, so we can't check them off yet.

**Comment by maxwellE** [comment]
Ill start on `alternate_icons` today

**Comment by brentleyjones** [comment]
`settings_bundle` needs some special `AppleResourceInfo` handling. It should work for BwB though as is.

**Comment by brentleyjones** [comment]
Closed as complete because the only remaining thing has it's own issue, and it's BwX only.
