### ISSUE TITLE
Support `macos_command_line_application`

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#99]
https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-macos.md#macos_command_line_application

- [x] #152
- [x] Support `infoplists`
  - [x] For targets with AppleBundleInfo: #225
  - [x] For targets with ObjcProvider: #234 
- [x] Support `provisioning_profile`
- [x] Support `codesignopts` #593
- [x] Support `exported_symbols_lists`: #649 
- [ ] Support `launchdplists`: #684

**Comment by maxwellE** [comment]
Sounds good @brentleyjones

**Comment by luispadron** [comment]
@brentleyjones we can mark the last task here completed as well.
